import { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "100 Daily Affirmations PDF",
    slug: "100-daily-affirmations",
    description: "Transform your mindset with 100 powerful daily affirmations designed to boost confidence and motivation.",
    price: 2000,
    type: "eBook",
    category: "quotes",
    image: "/images/products/affirmations.jpg",
    downloadUrl: "/sample-files/daily-affirmations.pdf",
    features: ["100 unique affirmations", "Printable format", "Daily tracking sheet"],
    creatorId: "creator1",
    creatorName: "Mindset Master",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    salesCount: 156,
    rating: 4.8,
  },
  {
    id: "2",
    title: "Morning Motivation Audio Pack",
    slug: "morning-motivation-audio-pack",
    description: "Start your day with energy and purpose. 30 days of morning motivation audio sessions.",
    price: 3200,
    type: "Audio",
    category: "audio",
    image: "/images/products/morning-motivation.jpg",
    downloadUrl: "/sample-files/morning-motivation.zip",
    features: ["30 audio sessions", "High quality MP3", "Accompanying workbook"],
    creatorId: "creator2",
    creatorName: "Audio Inspiration",
    createdAt: "2024-01-10T14:30:00Z",
    updatedAt: "2024-01-10T14:30:00Z",
    salesCount: 89,
    rating: 4.9,
  },
  {
    id: "3",
    title: "Success Mindset Toolkit",
    slug: "success-mindset-toolkit",
    description: "Complete toolkit for developing a success mindset. Includes worksheets, exercises, and daily practices.",
    price: 4800,
    type: "Bundle",
    category: "toolkit",
    image: "/images/products/success-toolkit.jpg",
    downloadUrl: "/sample-files/success-toolkit.zip",
    features: ["12-week program", "Interactive worksheets", "Video tutorials", "Community access"],
    creatorId: "creator3",
    creatorName: "Success Coach",
    createdAt: "2024-01-05T09:15:00Z",
    updatedAt: "2024-01-05T09:15:00Z",
    salesCount: 234,
    rating: 4.7,
  },
  {
    id: "4",
    title: "Productivity Planner 2025",
    slug: "productivity-planner-2025",
    description: "Comprehensive digital planner designed to maximize your productivity and achieve your goals.",
    price: 2800,
    type: "Planner",
    category: "planner",
    image: "/images/products/productivity-planner.jpg",
    downloadUrl: "/sample-files/productivity-planner.pdf",
    features: ["Yearly planning", "Monthly reviews", "Weekly templates", "Goal tracking"],
    creatorId: "creator4",
    creatorName: "Productivity Pro",
    createdAt: "2024-01-20T11:45:00Z",
    updatedAt: "2024-01-20T11:45:00Z",
    salesCount: 312,
    rating: 4.6,
  },
  {
    id: "5",
    title: "Confidence Building Guide",
    slug: "confidence-building-guide",
    description: "Step-by-step guide to building unshakeable confidence in any situation.",
    price: 2400,
    type: "eBook",
    category: "ebooks",
    image: "/images/products/confidence-guide.jpg",
    downloadUrl: "/sample-files/confidence-guide.pdf",
    features: ["Practical exercises", "Real-life examples", "Progress tracking"],
    creatorId: "creator5",
    creatorName: "Confidence Coach",
    createdAt: "2024-01-12T16:20:00Z",
    updatedAt: "2024-01-12T16:20:00Z",
    salesCount: 178,
    rating: 4.8,
  },
  {
    id: "6",
    title: "Meditation & Mindfulness Pack",
    slug: "meditation-mindfulness-pack",
    description: "Complete meditation and mindfulness program for stress relief and mental clarity.",
    price: 4000,
    type: "Audio",
    category: "audio",
    image: "/images/products/meditation-pack.jpg",
    downloadUrl: "/sample-files/meditation-pack.zip",
    features: ["Guided meditations", "Breathing exercises", "Mindfulness practices"],
    creatorId: "creator6",
    creatorName: "Mindful Living",
    createdAt: "2024-01-08T13:10:00Z",
    updatedAt: "2024-01-08T13:10:00Z",
    salesCount: 145,
    rating: 4.9,
  },
  {
    id: "7",
    title: "Quote Vault: Success & Motivation",
    slug: "quote-vault-success-motivation",
    description: "Curated collection of 500+ powerful quotes from successful entrepreneurs, leaders, and thinkers.",
    price: 1800,
    type: "Vault",
    category: "vault",
    image: "/images/products/quote-vault.jpg",
    downloadUrl: "/sample-files/quote-vault.pdf",
    features: ["500+ quotes", "Categorized by theme", "Printable cards", "Digital format"],
    creatorId: "creator7",
    creatorName: "Quote Collector",
    createdAt: "2024-01-18T10:30:00Z",
    updatedAt: "2024-01-18T10:30:00Z",
    salesCount: 267,
    rating: 4.7,
  },
  {
    id: "8",
    title: "Goal Achievement Blueprint",
    slug: "goal-achievement-blueprint",
    description: "Proven blueprint for setting and achieving any goal in your life.",
    price: 3600,
    type: "eBook",
    category: "ebooks",
    image: "/images/products/goal-blueprint.jpg",
    downloadUrl: "/sample-files/goal-blueprint.pdf",
    features: ["Goal setting framework", "Action planning", "Progress tracking", "Case studies"],
    creatorId: "creator8",
    creatorName: "Goal Getter",
    createdAt: "2024-01-14T15:45:00Z",
    updatedAt: "2024-01-14T15:45:00Z",
    salesCount: 198,
    rating: 4.8,
  },
]

// Function to create a new mock product
export function createMockProduct(productData: Partial<Product> & { title: string; creatorId: string; creatorName: string }): Product {
  const id = Math.random().toString(36).substr(2, 9)
  const now = new Date().toISOString()
  
  return {
    id,
    title: productData.title,
    slug: productData.slug || productData.title.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, ''),
    description: productData.description || '',
    price: productData.price || 0,
    type: productData.type || 'eBook',
    category: productData.category || 'quotes',
    image: productData.image || '/placeholder.svg?height=300&width=300&text=' + encodeURIComponent(productData.title),
    downloadUrl: productData.downloadUrl || '',
    features: productData.features || [],
    creatorId: productData.creatorId,
    creatorName: productData.creatorName,
    createdAt: now,
    updatedAt: now,
    salesCount: 0,
    rating: 0,
  }
} 